### PR TITLE
Fungicide

### PR DESCRIPTION
**Pull request by PaulMelloy**
Merge changes to add functionality of fungicide applications back into the `dev` branch

### CODE REVIEW

**Comment by PaulMelloy** [comment]
@adamhsparks do you have any comments on the changes made to incorporate fungicide applications?

**Review by adamhsparks — COMMENTED** [review]
https://github.com/PaulMelloy/ascomanageR/pull/1/commits/7d05526a2c2ae9ed98a6cf419170a670a86599fe#diff-5c4a64dedd7944a118ae084bd77097975992cd8b33e1ba367586f302a57d395b Line 124 is missing a closing "'".

**Comment by adamhsparks** [comment]
Line 171 of "format_weather.R" is missing a `call. = FALSE`

**Comment by adamhsparks** [comment]
Are there examples for using this functionality? I can't find anything in the vignette or a a new vignette or in the `trace_asco()` doc examples showing how to use this.

**Comment by PaulMelloy** [comment]
> Are there examples for using this functionality? I can't find anything in the vignette or a a new vignette or in the `trace_asco()` doc examples showing how to use this.

At the moment only within the `test_trace_asco`

**Pull request merged**
